name: Deploy Action 

on: 
  workflow_dispatch: # this workflow gets manually executed when commits merged into main 

jobs:
  deploy-via-semantic-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to push tags and commits 
    steps:
    - uses: actions/checkout@v3

    - run: npm ci

    - name: Run semantic-release
      uses: cycjimmy/semantic-release-action@v3
      with: 
        branch: latest # have this match what this workflow triggers on
        extra_plugins: |
          conventional-changelog-conventionalcommits
          @semantic-release/git
          @semantic-release/exec
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  major-version-update:
    runs-on: ubuntu-latest
    needs: [deploy-via-semantic-release] # wait for new git tag to be created before running 
    permissions:
      contents: write # to be able to push tags 
    steps:
    # Will automatically release vX for major releases after each deployment
    - uses: Actions-R-Us/actions-tagger@v2
      with:
        token: "${{ github.token }}"